name: 'Sync oktvbox Release'

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync oktvbox files
        run: |
          # 创建临时目录
          TEMP_DIR=$(mktemp -d)
          
          # 克隆源仓库到临时目录
          git clone --depth 1 --branch okjack --single-branch https://github.com/FongMi/Release.git "$TEMP_DIR"
          
          # 确保目标目录存在
          mkdir -p "Tvbox/Apk/Ok影视"
          
          # 复制文件
          cp -rf "$TEMP_DIR/apk/"* "Tvbox/Apk/Ok影视/"
          
          # 清理临时目录
          rm -rf "$TEMP_DIR"
          
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 添加更改
          git add "Tvbox/Apk/Ok影视"
          
          # 如果有更改则提交
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: sync oktvbox release"
            git push
          fi
