name: 'Sync Clash Repository'

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync Clash repository
        run: |
          mkdir -p clash
          cd clash
          if [ -z "$(ls -A)" ]; then
            git clone https://github.com/liandu2024/clash.git .
          else
            git remote set-url origin https://github.com/liandu2024/clash.git
            git fetch origin
            git reset --hard origin/main
          fi
